# RabbitMQ settings
rabbit.queue=statistic-queue
rabbit.exchange=statistic-exchange
rabbit.key=statistic-key
rabbit.dlq=statistic-dlq
rabbit.exchange-dlq=statistic-exchange-dlq
rabbit.key-dlq=statistic-dlq-key

# Rabbit configuration
rabbit.config.delay=${DELAY:5000}
rabbit.config.retry-backoff=${RETRY_BACKOFF:2}
rabbit.config.number-attempts=${NUMBER_ATTEMPTS:3}