server.port=8081
spring.application.name=statistic

# Database
spring.datasource.url=jdbc:postgresql://localhost:30643/statdb
spring.datasource.username=stat
spring.datasource.password=stat123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.jdbc=DEBUG

# Rabbit settings
rabbit